services:
  scrapy_service:
    build: .
    volumes:
      - ./app:/usr/src/app
      - ./projects:/projects
    user: ${MY_UID}:${MY_GID}
    tty: true
    stdin_open: true
    env_file:
      - .env.local
