services:
  scrapy_service:
    build: .
    volumes:
      - .:/usr/src
      - ./projects:/data/scraping-tool/projects
      - ./custom:/usr/src/custom
    user: ${MY_UID}:${MY_GID}
    tty: true
    stdin_open: true
    env_file:
      - path: .env.local
        required: false
