services:
  scrapy_service:
    build: .
    volumes:
      - ./app:/usr/src/app
    user: ${MY_UID}:${MY_GID}
    tty: true
    stdin_open: true
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    env_file:
      - .env.local
